---
namespace: alexbarton
name: boilerplate
version: 1.4.0

authors:
  - Alexander Barton <alex@barton.de>

description: Collection of boilerplate files, plays, roles and scripts for projects using Ansible.
readme: README.md

license_file: LICENSE

tags:
  - boilerplate
  - common
  - tools

dependencies:
  "community.general": ">=6.1.0"

homepage: https://github.com/alexbarton/ansible-collection-boilerplate
documentation: https://github.com/alexbarton/ansible-collection-boilerplate
issues: https://github.com/alexbarton/ansible-collection-boilerplate/issues
repository: https://github.com/alexbarton/ansible-collection-boilerplate

build_ignore:
  - .DS_Store
  - .cache
  - .trunk
  - .venv
  - dist
  - hosts.ini
  - site.yml
