#!/bin/bash
#
# description=Show documentation.
#

set -euo pipefail

# Show usage information on stderr.
#
Usage_Exit() {
	{
		echo "ansible-boilerplate docs <topic>"
		echo
	} >&2
	exit "${1:-1}"
}

case "${1-}" in
"")
	Usage_Exit
	;;
"help" | "--help")
	Usage_Exit 0
	;;
*)
	# Continue!
	;;
esac

# Run ansible(1):
set -x
exec ansible-doc "$@"
