---
# Connect to a system and run the Ansible "ping" module on it.
#
# Example:
# ./bin/ap ping -l example.host.name
#

- name: Ping system
  hosts: '{{target|default("all")}}'
  gather_facts: false

  tasks:

    - name: Run the Ansible "ping" module
      ansible.builtin.ping:
